### ISSUE TITLE
Running application with application plugin

### ISSUE THREAD

**Issue by dinnymate** [gradle-clojure/gradle-clojure#107]
I tried using gradle-clojure but i cant run my app. I set the mainClassName to the clojure namespace but nothing happens. How can i run the app?

**Comment by dinnymate** [comment]
My ns does contain the gen-class keyword and has a main method. I actually realized that running the jar directly does not work either. It says 

> Error: Could not find or load main class hu.telekiblanka.studio.dashboard.server.bootstrap.core

I looked into the jar and the generated class is there and manifest looks okay to me. Here is my build.gradle:

`plugins {
    id "gradle-clojure.clojure" version "0.4.0"
    id "java"
    id "application"
}

group 'hu.telekiblanka.studio'
version '0.0.1'

mainClassName = "hu.telekiblanka.studio.dashboard.server.bootstrap.core"

repositories {
    jcenter()
    mavenCentral()
    maven {
        url("http://clojars.org/repo")
    }
}

dependencies {
    implementation 'org.clojure:clojure:1.9.0'

    implementation "org.clojure:java.jdbc:0.7.7"
    implementation "org.postgresql:postgresql:9.4-1206-jdbc42"
    implementation 'org.hibernate:hibernate-core:5.3.3.Final'
    implementation 'javax.xml.bind:jaxb-api:2.3.0'
    implementation 'com.sun.xml.bind:jaxb-impl:2.3.0.1'
    implementation 'com.sun.xml.bind:jaxb-core:2.3.0.1'

    implementation 'ring:ring-core:1.6.3'
    implementation 'ring:ring-devel:1.6.3'
    implementation 'ring:ring-json:0.5.0-beta1'
    implementation 'ring:ring-jetty-adapter:1.6.3'
    implementation 'hiccup:hiccup:1.0.5'

    implementation 'compojure:compojure:1.6.1'

    testImplementation 'junit:junit:4.12'

    devImplementation 'org.clojure:tools.namespace:0.3.0-alpha4'
}

sourceSets {
    main {
        output.dir("$buildDir/frontend", builtBy: 'buildFrontend')
    }
}

clojureRepl {
    port 7111
}

task installFrontendDeps(type:Exec){
    workingDir = "./src/frontend"
    commandLine "yarn", "install"
}
task buildFrontend(type:Exec,dependsOn: installFrontendDeps) {
    doFirst {
        delete("$buildDir/frontend")
    }
    workingDir = "./src/frontend"
    commandLine "yarn", "build"
}

task watchFrontend(type:Exec,dependsOn: installFrontendDeps) {
    doFirst {
        delete("$buildDir/frontend")
    }
    workingDir = "./src/frontend"
    commandLine "yarn", "dev"
}

task stage(type: Jar) {
    manifest {
        attributes 'Main-Class': 'hu.telekiblanka.studio.dashboard.server.bootstrap.core'
    }
    // pack yours main module
    from sourceSets.main.output
    // pack all dependencies in the project
    from configurations.compile.collect { it.isDirectory() ? it : zipTree(it) }
}
`

**Comment by ajoberstar** [comment]
Looks like you just need to enable AOT compilation.

Either:

```
clojure.builds {
  main {
    aotAll()
  }
}
```

Or:

```
clojure.builds {
  main {
    aotNamespaces = ['whatever.namespace']
  }
}
```

This is documented well, but these options can be seen [here](https://gradle-clojure.github.io/gradle-clojure/).

**Comment by dinnymate** [comment]
Thank you. It works now!
