### ISSUE TITLE
:gen-class violates Spotbugs CN_IMPLEMENTS_CLONE_BUT_NOT_CLONEABLE

### ISSUE THREAD

**Issue by mcandre** [gradle-clojure/gradle-clojure#114]
## Expected Behavior

Basic Clojure classes pass Spotbugs checks.

## Current Behavior

With default configuration, spotbugs reports `<your.class.here> defines clone() but doesn't implement Cloneable`. I'm not sure if this an issue with the gradle-plugin or with Clojure itself, would like a second opinion on this.

## Steps to reproduce

Add spotbugs to `build.gradle`:

```gradle
plugins {
    id 'gradle-clojure.clojure' version '0.5.0-alpha.1'
    id 'com.github.spotbugs' version '1.6.9'
}

apply plugin: 'com.github.spotbugs'

spotbugs {
    sourceSets = [sourceSets.main]
}

tasks.withType(com.github.spotbugs.SpotBugsTask) {
    reports {
        xml.enabled = false
        html.enabled = true
    }
}
```

Then run `gradle check`.

Then open the resulting HTML report in `build/reports/spotbugs/main.html`.

## Workaround

I am temporarily disabling this rule for my Clojure projects in a spotbugs `excludes.xml`:

```xml
<Match>
    <Bug pattern="CN_IMPLEMENTS_CLONE_BUT_NOT_CLONEABLE" />
</Match>
```

## Environment

```console
$ gradle --version

------------------------------------------------------------
Gradle 5.1.1
------------------------------------------------------------

Build time:   2019-01-10 23:05:02 UTC
Revision:     3c9abb645fb83932c44e8610642393ad62116807

Kotlin DSL:   1.1.1
Kotlin:       1.3.11
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          11.0.2 (Oracle Corporation 11.0.2+9)
OS:           Mac OS X 10.14.2 x86_64
```

**Comment by ajoberstar** [comment]
I'll be responding to #115 about SpotBugs in general, but considering these all won't fix as there's no clear problem in gradle-clojure.
