### ISSUE TITLE
Integration issue with Spotbugs filter by source

### ISSUE THREAD

**Issue by mcandre** [gradle-clojure/gradle-clojure#115]
## Expected Behavior

Spotbugs filter exclusions can be configured to remove certain rules violated by classes generated from Clojure source code files.

## Current Behavior

Somehow, the Gradle spotbug plugin is able to match `<Source name="~.*\.groovy" />` but not `<Source name="~.*\.clj" />`. So `gradle check` ends up ignoring exclusion filters meant to turn off rules affecting my Clojure code.

## Steps to reproduce

Add spotbugs to build.gradle:

```gradle
plugins {
    id 'com.github.spotbugs' version '1.6.9'
}

apply plugin: 'com.github.spotbugs'

spotbugs {
    sourceSets = [sourceSets.main]
    excludeFilter = file("${rootProject.projectDir}/config/spotbugs/exclude.xml")
}
```

Add some `<Source name=`... rule matches in `exclude.xml`.

Then run `gradle check`.

## Workaround

Given that `:gen-class` appears to require class names to be lowercase for gradle-clojure, I am working around the above limitation by applying spotbugs filter exclusions based on class names that begin with a lowercase letter. Here's a small working example `excludes.xml`:

```xml
<FindBugsFilter>
    <Match>
        <Source name="~.*[a-z].*" />
        <Bug pattern="NM_CLASS_NAMING_CONVENTION" />
    </Match>
    <Match>
        <Source name="~.*[a-z].*" />
        <Bug pattern="CN_IMPLEMENTS_CLONE_BUT_NOT_CLONEABLE" />
    </Match>
</FindBugsFilter>
```

## Environment

```console
$ gradle --version

------------------------------------------------------------
Gradle 5.1.1
------------------------------------------------------------

Build time:   2019-01-10 23:05:02 UTC
Revision:     3c9abb645fb83932c44e8610642393ad62116807

Kotlin DSL:   1.1.1
Kotlin:       1.3.11
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          11.0.2 (Oracle Corporation 11.0.2+9)
OS:           Mac OS X 10.14.2 x86_64
```

**Comment by ajoberstar** [comment]
SpotBugs won't integration won't be directly supported by gradle-clojure, but if there's something we can improve to make it compatible, that would be on the table.

From a quick scan around their documentation, it's not clear how these source filters work. It may be worth reviewing the SpotBugs output for your Clojure classes to see if it tells you where it thinks the source is.

**Comment by ajoberstar** [comment]
Closing due to lack of response. Feel free to reopen, if you want to continue discussing this.
