### ISSUE TITLE
:gen-class violates Spotbugs EC_UNRELATED_TYPES_USING_POINTER_EQUALITY

### ISSUE THREAD

**Issue by mcandre** [gradle-clojure/gradle-clojure#116]
## Expected Behavior

Java classes generated with `:gen-class` from Clojure sources pass Spotbugs default checks.

## Current Behavior

When spotbugs is enabled, `gradle check` creates a spotbugs report containing `EC_UNRELATED_TYPES_USING_POINTER_EQUALITY` violations on `(cond`... equality expressions. I am not sure if this an issue with gradle-clojure or with Clojure itself. Maybe someone could shed light on this?

## Steps to reproduce

1. Use `(cond`... equality checks in Clojure source, such as between function parameters and numeric values (int, float, double, etc.)
2. Add Spotbugs to build.gradle with HTML output.
3. Run `gradle check`.
4. Then open `build/reports/spotbugs/main.html`.

## Workaround

I am configuring Spotbugs exclusion filters in my `excludes.xml`:

```xml
<FindBugsFilter>
    <Match>
        <Source name="~.*[a-z].*" />
        <Bug pattern="EC_UNRELATED_TYPES_USING_POINTER_EQUALITY" />
    </Match>
</FindBugsFilter>
```

## Environment

```console
$ gradle --version

------------------------------------------------------------
Gradle 5.1.1
------------------------------------------------------------

Build time:   2019-01-10 23:05:02 UTC
Revision:     3c9abb645fb83932c44e8610642393ad62116807

Kotlin DSL:   1.1.1
Kotlin:       1.3.11
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          11.0.2 (Oracle Corporation 11.0.2+9)
OS:           Mac OS X 10.14.2 x86_64
```

**Comment by ajoberstar** [comment]
I'll be responding to #115 about SpotBugs in general, but considering these all won't fix as there's no clear problem in gradle-clojure.
