### ISSUE TITLE
Specify port that the repl starts on

### ISSUE THREAD

**Issue by tanelso2** [gradle-clojure/gradle-clojure#118]
## Desired Behavior

Instead of picking a random port every time, we should be able to specify a port that the repl will start on.

## Context

Every time I restart the REPL, I have to change my IntelliJ remote REPL connection configuration. I would like that to remain static so I don't have to deal with it.

**Comment by tanelso2** [comment]
I would like to work on this myself as a short introductory pull request. 

I found in the code where the REPL is created and the port is selected. Now I just need to learn how to add fields to the DSL that gets added to build.gradle so that I can specify the port number in there.

Any pointers would be appreciated, but I can probably figure it out by myself given enough time.

**Comment by ajoberstar** [comment]
Hi Tom, This is supported already; see the `ClojureNRepl` section in [main doc](https://gradle-clojure.github.io/gradle-clojure/). Can specify in the `build.gradle` or as an argument.

**Comment by tanelso2** [comment]
Wow sorry apparently I am really bad at reading the documentation. Sorry! Thanks for the heads up
