### ISSUE TITLE
0.1.0 Release and 0.2.0 Planning

### ISSUE THREAD

**Issue by ajoberstar** [gradle-clojure/gradle-clojure#13]
@gradle-clojure/developers I've completed everything that I think we wanted in [the first release](https://github.com/gradle-clojure/gradle-clojure/milestone/1?closed=1). This is just a port of the code from the cursive repo to this one, with the inclusion of with @pbzdyl's work on incremental builds. The main code is ported to Java and the tests are ported to Clojure. The code's not pretty at this point, but I tried to keep it as one-to-one as possible with the old code as a first step.

This has been released to the plugin portal as `gradle-clojure.clojure` (currently version 0.1.0-rc.3). Please peruse the code and test out the plugin, if you have some time. It should behave identically to the old plugin, so it should be as simple as swapping `com.cursive-ide.clojure` for `gradle-clojure.clojure`.

There's also a draft list of issues for [0.2.0](https://github.com/gradle-clojure/gradle-clojure/milestone/2) for your review also. Generally, the goal would be to stay functionally equivalent, but get the code updated to general Gradle conventions and switch over to some of the 4.x APIs.

I plan to make more progress on the plugin this week/weekend. Now that the first run of porting is complete, I'll switch to PRs exclusively to make reviews/collaboration easier.

What I'm looking for from you (if you have time):

1. Does this 0.1.0 release look good (I'll cut the final, if so)?
1. Any general thoughts on the code/structure/build setup?
1. Anything you want in or out of 0.2.0?
1. Any issues you want to work on?

Also please start throwing more issues out for feature ideas for future releases.

**Comment by jszakmeister** [comment]
@ajoberstar Sorry I've been quiet... I've been traveling lately and don't have great Internet access.  I'll try and take a look the release today and try to let you know any feedback tomorrow.  And thank you for running with this and getting things going!

**Comment by ajoberstar** [comment]
No problem, @jszakmeister. Look forward to the feedback.

**Comment by jszakmeister** [comment]
@ajoberstar As a first cut, it looks good to me.  I agree with everything you pointed out (moving things to their own class files, an internal API area, reducing the usage on Gradle internal APIs, using the Gradle workers, etc.).  I haven't had a chance to look at your pull requests in detail yet, but from the commit messages it definitely seems headed the right way!

**Comment by ajoberstar** [comment]
Sounds good, I just cut 0.1.0.

**Comment by pbzdyl** [comment]
@ajoberstar Thank you for all your work so far. Unfortunately I haven't had time to test the 0.1.0 version yet and it also lacks some of the features that we have in our fork of the plugin (e.g. support for a custom test running script replacing the one bundled in the plugin).

Hopefully, I will have some time soon to test it with my "test" projects to see how the 0.1.0 works.

**Comment by ajoberstar** [comment]
No problem, @pbzdyl. Thanks for adding some feedback in the issues.
