### ISSUE TITLE
Switch to JUnit4 clojure.test runner

### ISSUE THREAD

**Issue by ajoberstar** [gradle-clojure/gradle-clojure#17]
Currently, we generate a separate task `ClojureTest` that will scan for test namespaces and call `clojure.test/run-tests` on them. This does provide a good way to utilize the out-of-the-box clojure.test runner and get it into Gradle without much effort.

The main disadvantage is the lack of parity with the JUnit/TestNG based `Test` task in Gradle core. That task provides test filtering from the command line `./gradlew test --tests my.package.*`, configurable logging of test progress, Tooling API integration, HTML reports. Integrating with this task would make our plugin feel more native to Gradle.

Right now, the only way to integrate into this is by using a custom JUnit4 `Runner`. Gradle then requires that there be class file(s) in the test classes dir that have an `@RunWIth` annotation specifying this runner. This could involve each test namespace including a `(:gen-class)` decl that specifies that annotation and our custom runner. The other option (that we're currently using in the compatTests) is to generate a single, otherwise empty class, with the `@RunWith` annotation. The runner then is responsible for scanning the test source directory to identify the actual test vars. You can see the source of [the runner being used for the compat tests here](https://github.com/gradle-clojure/gradle-clojure/blob/master/src/compatTest/clojure/gradle_clojure/compat_test/test_runner.clj).

The behavior is pretty good with the single class, minus some issues with where the stdout/stderr of once-fixtures go. We would get better behavior if each namespace had the annotation, but that either requires someone to specify this in all of their source files (which seems like a major con), or we would somehow have to inject that gen-class behavior. Not sure if/how we could do that.

Long-term I would prefer to leverage JUnit 5, which provides a much cleaner approach for integrating other test frameworks. At the moment, that is still not integrated into Gradle.

**Comment by pbzdyl** [comment]
This would be a really nice enhancement and would let us use standard Gradle/JUnit reporting so we don't have to plug into clojure.test multimethods to get both: console reports and JUnit XML report for our CI.

Using JUnit 5 would be indeed much easier to implement on our side but we need to wait for its support in Gradle's Test task.

I was thinking about injecting the gen-class behaviour - would it be possible to generate a ns with gen-class etc. per each ns that would wrap the original ns?
