### ISSUE TITLE
Basic REPL support

### ISSUE THREAD

**Issue by ajoberstar** [gradle-clojure/gradle-clojure#27]

**Comment by ajoberstar** [comment]
Thinking of starting with socket REPL and doing nREPL separately.

**Comment by ajoberstar** [comment]
Would want to leverage gradle/gradle#2336 (deployment API, currently used by Play integration). Can try the internal API for now to just see how it works.

**Comment by ajoberstar** [comment]
Also need to address user input at some point, but for now might be nice to just have something kicked off and handle start/stop. Have user connect outside of Gradle to interact.

**Comment by pbzdyl** [comment]
At some point it would be good to have Cider support added (not in this plugin but in Cider) to allow jack-in via gradle task as it is now possible with lein/boot.

**Comment by camechis** [comment]
I thought cider already supports this, I know there is some gradle support
there.

**Comment by ajoberstar** [comment]
Looks like [Cider added clojuresque support](https://github.com/clojure-emacs/cider/issues/1373). Didn't look closely enough to tell if we can leverage that or it we'd need something else.

**Comment by ajoberstar** [comment]
FYI, switched from socket first to nrepl first. Seems like that has more practical use.
