### ISSUE TITLE
0.3.0 Planning

### ISSUE THREAD

**Issue by ajoberstar** [gradle-clojure/gradle-clojure#32]
@gradle-clojure/developers Right now, I'm thinking we'd target:

- #17 Using Gradle' `Test` task (i.e. JUnit4) to run `clojure.test`
- #27 basic REPL support

Any other thoughts on what would be good for the next release (or concerns about either of the two above). For REPL support, I'd be interested in feedback in that issue for how we should tackle it for now. I see some issues related to allowing user input in Gradle's backlog, so we may be able to get more natural support eventually.

**Comment by aadrian** [comment]
> Any other thoughts on what would be good for the next release 

ClojureScript support would be very useful, but if it's planned for 0.4.0 is also cool :) 

OT: @ajoberstar is there any other way to be able to extend the `gradle init` https://docs.gradle.org/current/userguide/build_init_plugin.html task?  (SBT can have random templates: http://www.scala-sbt.org/0.13/docs/sbt-new-and-Templates.html  )
Would be very useful (and many more would try this plug-in) if by simply calling `gradle init --type=clojure-library` we could create a standard project with Clojure.

**Comment by ajoberstar** [comment]
@aadrian I'd lean towards 0.4.0 for ClojureScript to keep it manageable.

Build in it extensibility is an [open issue for Gradle](https://github.com/gradle/gradle/issues/1686).

**Comment by ajoberstar** [comment]
Hearing no objections, [0.3.0](https://github.com/gradle-clojure/gradle-clojure/milestone/3) will focus on JUnit and REPL.
