### ISSUE TITLE
Mixing Java and Clojure files

### ISSUE THREAD

**Issue by anolivetree** [gradle-clojure/gradle-clojure#40]
Hello,

Is mixing Java and Clojure files supported? I tried to call a method in AOT-compiled Clojure class from Java, but "gradlew compileJava" failed because javac cannot see the classes located in build/classes/main/clojure/.

If it's not currently supported, are there any plan to support it?

**Comment by ajoberstar** [comment]
We do intend to support polyglot projects (one of our key goals in fact). This 0.3.0 though is the first that puts us over the hump of feeling usable for Clojure-only (now that we have REPL support).

The big issue is that some JVM language plugins can get bi-directional Java <-> _Other_ support. They usually have some kind of joint compilation, where they generate stub classes of their language for Java to reference at compile time, then they compile their language against the resulting compiled Java classes.

I don't think we can pull that off for Clojure (at least in the near term), so there's probably a question of which direction makes the most sense to support (or should we just document how you would do this).

Just from my gut I would have expected Clojure depending on Java to be more common, but obviously you're an example where the opposite is true.

Short term, it takes some fiddling with sourceSets and task dependencies in your build script. I don't have that off the top of my head, but it should be possible.

**Comment by ajoberstar** [comment]
The Groovy plugin will be default configure it so `compileGroovy` depends on `compileJava` and the output of `compileJava` is on the classpath of `compileGroovy`. Again this doesn't help with your use case (though you could do the opposite). 

If we aligned with that approach you could get easy Clojure depends on Java. But Groovy has joint compilation to get the Java depends on Groovy. Clojure doesn't, so not sure how we make that easy.

**Comment by aadrian** [comment]
> The big issue is that some JVM language plugins can get bi-directional Java <-> Other support ...
> I don't think we can pull that off for Clojure (at least in the near term),

If this bi-directionality would be in fact uni-directional (the one or the other direction) e.g. at the package level, would it be easier to achieve?

e.g. the user would have to define something like:
```
packageDeps {
   package_1 dependesOn ns_A
   ns_B dependsOn package_2
   package 3 depndsOn ns_C
}
```
> so there's probably a question of which direction makes the most sense to support (or should we just document how you would do this)

Documenting how to achieve each direction would be more useful in the beginning.

>  I would have expected Clojure depending on Java to be more common ...

Sneaking Clojure into existing (Gradle based) projects would open many new uses :) .

**Comment by ajoberstar** [comment]
May want to consider [how Leiningen does this](https://github.com/technomancy/leiningen/blob/master/doc/MIXED_PROJECTS.md). Have to read it more closely to figure out the default. For their interleaving piece, that's where we'd have to document how to make more source sets and have them depend on each other in the preferred order.

**Comment by ajoberstar** [comment]
> > The big issue is that some JVM language plugins can get bi-directional Java <-> Other support ...
> > I don't think we can pull that off for Clojure (at least in the near term),
> 
> If this bi-directionality would be in fact uni-directional (the one or the other direction) e.g. at the package level, would it be easier to achieve?
> 
> e.g. the user would have to define something like:
> ```
> packageDeps {
>    package_1 dependesOn ns_A
>    ns_B dependsOn package_2
>    package 3 depndsOn ns_C
> }
> ```

I think doing it at the sourceSet level most easily integrate with Gradle's general features. Package level would probably have to replicate the functionality already provided by source sets, so it could be troublesome.

> > so there's probably a question of which direction makes the most sense to support (or should we just document how you would do this)
> 
> Documenting how to achieve each direction would be more useful in the beginning.

Agreed.

**Comment by ajoberstar** [comment]
The fix is part of 0.3.0. Please reopen if this didn't fix the issue.

**Comment by ajoberstar** [comment]
Also see the docs directory for documentation on your use case. (The other direction is now supported by default)

**Comment by anolivetree** [comment]
Thank you!
