### ISSUE TITLE
ClojureWorker may be causing some app-related classes to load from the wrong classloader

### ISSUE THREAD

**Issue by ajoberstar** [gradle-clojure/gradle-clojure#51]
## Expected Behavior

Having slf4j and logback on the compile classpath, should result in being able to log from the REPL.

## Current Behavior

The REPL prints out a warning from SLF4J:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder".
SLF4J: Defaulting to no-operation MDCAdapter implementation.
SLF4J: See http://www.slf4j.org/codes.html#no_static_mdc_binder for further details.
```

This seems to imply it might be seeing SLF4J in a parent classloader (e.g. the one from Gradle) and thus not seeing the Logback in our app classloader.

## Environment

| **Component**  | **Version** |
|----------------|-------------|
| gradle-clojure | 0.3.0 |
| Gradle         | 4.3 |
| Java           | 9.0.1 |
| OS             | Windows 10 |

**Comment by ajoberstar** [comment]
Similar to some behavior @pbzdyl noted in #28, we may benefit from a parent-last classloader being used by the worker (or considering dropping the use of the worker API).

**Comment by pbzdyl** [comment]
There might be an issue with Gradle classloader isolation in Workers: https://discuss.gradle.org/t/guava-in-gradles-classpath/24861/8. Let's see if it will be confirmed.

**Comment by pbzdyl** [comment]
I think #52 might be related to ClojureWorker retaining some state across ClojureCompile task invocation.

**Comment by ajoberstar** [comment]
One piece we're not doing in the workers is "refreshing" all of the namespace/state in the shimdandy runtime. We wanted to save some clojure startup time, but not pollute future runs.
