### ISSUE TITLE
Can't get java to compile when calling clojure code

### ISSUE THREAD

**Issue by willh33** [gradle-clojure/gradle-clojure#57]
## Adding clojure to an already existing gradle java project

_I have a java project that I want to start trying to add some clojure to, but I'm hitting a few issues. I'm not sure this is the right place to post this, but was hoping you would be able to help. I'm using the intellij IDE with the Cursive for clojure intellij plugin. I am also using this gradle plugin for clojure. My java classes recognize and can call my clojure code, but my java code will no longer compile because at compile time it can no longer see my clojure code. Do I need to add an extra step in my build.gradle? Do I need to compile them separately manually before trying to compile java? Any help would be appreciated. Also if this is not the correct place to post, can you point me in the right direction?_

## Environment

| **Component**  | **Version** |
|----------------|-------------|
| gradle-clojure | _0.3.1_ |
| Gradle         | _4.4.1_ |
| Java           | _1.8_ |
| OS             | _Mac OS High Sierra_ |

## Logs

**Switches used:** _e.g. --info --stacktrace_

```
<> Task :compileJava FAILED
java:8: error: cannot find symbol 
import com.example.clojure;
>
```

**Comment by jszakmeister** [comment]
Yes, you need to set a build dependency.  Check out the [docs](https://github.com/gradle-clojure/gradle-clojure/tree/master/docs#java-that-depends-on-clojure).  Hope that helps!

**Comment by willh33** [comment]
Thank you for the response, how do I set a build dependency? I've looked at the docs and I must not understand them because I still can't seem to get it working,



Sent from my T-Mobile 4G LTE Device


-------- Original message --------

**Comment by jszakmeister** [comment]
You might need to add something like:

    compileJava.depends on compileClojure

Into your build.gradle.  But you need the other bits to make sure that the classpath is setup correctly.  Gradle fairly recently started separating out the compiled class files for different languages, so things are a bit different than they've traditionally been.

**Comment by ajoberstar** [comment]
If you look at the bottom of that docs page there's a section on Java code that depends on Clojure code. You'll need to declare another source set and configure the dependencies as noted there. You'll likely also need to enable aot compile on the Clojure compile task.

**Comment by willh33** [comment]
When I was able to get my Java code to see my clojure code before compile time my directory structure had both the clojure and java directories in src/main

To structure it like the docs I created another sourceSet so my structure now looks like this:
![image](https://user-images.githubusercontent.com/7401061/34888231-acf53d36-f786-11e7-805c-6e6fe5b219a4.png)
and now my java code can't see my clojure code.
Here is my compileClojure options 
![image](https://user-images.githubusercontent.com/7401061/34888298-017150f2-f787-11e7-9125-46596a391ec7.png)
(The options that are commented out could not build, it says: 
`Could not set unknown property 'projectOnly' for task ':compileClojure'`)

Here is where I import the gradle-clojure plugin:
![image](https://user-images.githubusercontent.com/7401061/34888328-1ebc17b4-f787-11e7-8e79-552c5dbb36df.png)

And here is where i declare the extra sourceSet 
![image](https://user-images.githubusercontent.com/7401061/34888401-6a639f70-f787-11e7-9b5c-034f9d99913b.png)

**Comment by ajoberstar** [comment]
I think all you need is:

```groovy
sourceSets {
  pre
  main.compileClasspath += pre.output
}

configurations {
  preCompile.extendsFrom compile
}

compilePreClojure {
  options.aotCompile = true
}
```
Particularly note the last piece. You want to configure the compile task for  the `pre` source set, not the `main` source set. You don't need and likely don't want most of those compile options you included. They're in the doc as examples, but you generally don't need many, if any, of them.

**Comment by ajoberstar** [comment]
Feel free to reopen if this hasn't solved your issue.
