### ISSUE TITLE
Compile options can't be set via a closure

### ISSUE THREAD

**Issue by ajoberstar** [gradle-clojure/gradle-clojure#63]
## Expected Behavior

As documented you should be able to do something like:

```groovy
compileClojure {
  options.aotCompile = true

  options.reflectionWarnings {
    enabled = true
    asErrors = true
  }
}
```

## Current Behavior

To get it to work, you need to do:

```groovy
compileClojure {
  options.aotCompile = true

  options.reflectionWarnings { w ->
    w.enabled = true
    w.asErrors = true
  }
}
```

or:

```groovy
compileClojure {
  options.aotCompile = true

  options.reflectionWarnings.enabled = true
  options.reflectionWarnings.asErrors = true
}
```

## Environment

| **Component**  | **Version** |
|----------------|-------------|
| gradle-clojure | 0.3.1 |
| Gradle         | 4.6 |
| Java           | 10 |
| OS             | Windows 10 |

## Logs

**Switches used:** none

```
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\andre\projects\gradle-clojure-talk\build.gradle' line: 32

* What went wrong:
A problem occurred evaluating root project 'gradle-clojure-talk'.
> Could not set unknown property 'asErrors' for task ':compileClojure' of type gradle_clojure.plugin.tasks.ClojureCompile.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
```

**Comment by ajoberstar** [comment]
I think the issue is [how we are calling the config actions](https://github.com/gradle-clojure/gradle-clojure/blob/aed299298b026547d8651efd952f617facacb928/modules/gradle-clojure-plugin/src/main/java/gradle_clojure/plugin/tasks/ClojureCompileOptions.java#L76). From the Groovy side, we need to set to do the whole "delegate first" deal to make sure it tries to set `asErrors` and `enabled` on the `ReflectionWarnings` instead of the task.

I thought Gradle was going to deal with the sugar for that, but it must take more from our side to get that to happen.

**Comment by pbzdyl** [comment]
I noticed the same issue with:

```
options.forkOptions {
    ....
}
```

Using `options.forkOptions.<propertyName>` works fine.

**Comment by ajoberstar** [comment]
I believe we just have to create those objects with Gradle's ObjectFactory. Ran into this on another plugin.

**Comment by ajoberstar** [comment]
I was wrong, not the ObjectFactory. See [their guide on this](https://guides.gradle.org/implementing-gradle-plugins/?_ga=2.164544895.1102250615.1524192625-656059790.1518825644#modeling_dsl_like_apis) particularly noting the sentence at the end of that section:

> If you need second- or third-level nesting, you will also have to add overloads that take a Closure, because Gradle cannot instrument nested extensions at the moment.

So we just need to add overloads. (Working on this now)
